// Code generated by sqlc. DO NOT EDIT.

package query

import (
	"database/sql"
	"encoding/json"
	"time"
)

type LikedPost struct {
	Username string
	PostID   int64
	LikedAt  time.Time
}

type Post struct {
	ID          int64
	Username    string
	CoverHash   sql.NullString
	Images      []string
	Description sql.NullString
	Tags        []string
	Location    sql.NullString
}

type PrivateUser struct {
	Username        string
	DisplayName     sql.NullString
	Avatar          sql.NullString
	Bio             sql.NullString
	Birthday        sql.NullTime
	FoodPreferences json.RawMessage
}

type PublicUser struct {
	Username    string
	DisplayName sql.NullString
	Avatar      sql.NullString
	Bio         sql.NullString
}

type Session struct {
	Token    string
	Username string
	Expiry   time.Time
	Metadata json.RawMessage
}

type User struct {
	Username        string
	Passhash        []byte
	DisplayName     sql.NullString
	Avatar          sql.NullString
	Bio             sql.NullString
	Birthday        sql.NullTime
	FoodPreferences json.RawMessage
}
