// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/discord-gophers/goapi-gen version (devel) DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"encoding/xml"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	openapi_types "github.com/discord-gophers/goapi-gen/pkg/types"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/render"
)

// Error object returned on any error
type Error struct {
	Message string `json:"message"`
}

// FoodPreferences defines model for FoodPreferences.
type FoodPreferences struct {
	Likes   []string                `json:"likes"`
	Prefers FoodPreferences_Prefers `json:"prefers"`
}

// FoodPreferences_Prefers defines model for FoodPreferences.Prefers.
type FoodPreferences_Prefers struct {
	AdditionalProperties map[string][]string `json:"-"`
}

// Snowflake ID
type ID int64

// Optional metadata included on login
type LoginMetadata struct {
	// The User-Agent used for logging in
	UserAgent *string `json:"user_agent,omitempty"`
}

// Post defines model for Post.
type Post struct {
	CoverHash   *string `json:"cover_hash,omitempty"`
	Description string  `json:"description"`

	// Snowflake ID
	ID     ID       `json:"id"`
	Images []string `json:"images"`

	// Location is the location where the post was made.
	Location *string  `json:"location,omitempty"`
	Tags     []string `json:"tags"`

	// Snowflake ID
	UserID ID `json:"user_id"`
}

// Self defines model for Self.
type Self struct {
	// Embedded struct due to allOf(#/components/schemas/User)
	User `yaml:",inline"`
	// Embedded fields due to inline allOf schema
	Birthday openapi_types.Date `json:"birthday"`
}

// Session defines model for Session.
type Session struct {
	Expiry time.Time `json:"expiry"`

	// Optional metadata included on login
	Metadata *LoginMetadata `json:"metadata,omitempty"`
	Token    string         `json:"token"`

	// Snowflake ID
	UserID ID `json:"user_id"`
}

// User defines model for User.
type User struct {
	Avatar string  `json:"avatar"`
	Bio    *string `json:"bio,omitempty"`

	// Snowflake ID
	ID   ID     `json:"id"`
	Name string `json:"name"`
}

// UserLikedPosts defines model for UserLikedPosts.
type UserLikedPosts struct {
	// Expires is the time that the rate limiter (the Remaining field) replenishes.
	Expires time.Time `json:"expires"`

	// Posts maps post IDs to the time that the user liked.
	Posts UserLikedPosts_Posts `json:"posts"`

	// Remaining is the number of likes allowed by the user until the Expires timestamp.
	Remaining float32 `json:"remaining"`
}

// Posts maps post IDs to the time that the user liked.
type UserLikedPosts_Posts struct {
	AdditionalProperties map[string]time.Time `json:"-"`
}

// Error object returned on any error
type N4xX Error

// LoginParams defines parameters for Login.
type LoginParams struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

// RegisterParams defines parameters for Register.
type RegisterParams struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

// GetUsersIDParams defines parameters for GetUsersID.
type GetUsersIDParams struct {
	Password string `json:"password"`
}

// Response is a common response struct for all the API calls.
// A Response object may be instantiated via functions for specific operation responses.
type Response struct {
	body        interface{}
	statusCode  int
	contentType string
}

// Render implements the render.Renderer interface. It sets the Content-Type header
// and status code based on the response definition.
func (resp *Response) Render(w http.ResponseWriter, r *http.Request) error {
	w.Header().Set("Content-Type", resp.contentType)
	render.Status(r, resp.statusCode)
	return nil
}

// Status is a builder method to override the default status code for a response.
func (resp *Response) Status(statusCode int) *Response {
	resp.statusCode = statusCode
	return resp
}

// ContentType is a builder method to override the default content type for a response.
func (resp *Response) ContentType(contentType string) *Response {
	resp.contentType = contentType
	return resp
}

// MarshalJSON implements the json.Marshaler interface.
// This is used to only marshal the body of the response.
func (resp *Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(resp.body)
}

// MarshalXML implements the xml.Marshaler interface.
// This is used to only marshal the body of the response.
func (resp *Response) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return e.Encode(resp.body)
}

// LoginJSON200Response is a constructor method for a Login response.
// A *Response is returned with the configured status code and content type from the spec.
func LoginJSON200Response(body Session) *Response {
	return &Response{
		body:        body,
		statusCode:  200,
		contentType: "application/json",
	}
}

// LoginJSON400Response is a constructor method for a Login response.
// A *Response is returned with the configured status code and content type from the spec.
func LoginJSON400Response(body Error) *Response {
	return &Response{
		body:        body,
		statusCode:  400,
		contentType: "application/json",
	}
}

// RegisterJSON200Response is a constructor method for a Register response.
// A *Response is returned with the configured status code and content type from the spec.
func RegisterJSON200Response(body Session) *Response {
	return &Response{
		body:        body,
		statusCode:  200,
		contentType: "application/json",
	}
}

// RegisterJSON400Response is a constructor method for a Register response.
// A *Response is returned with the configured status code and content type from the spec.
func RegisterJSON400Response(body Error) *Response {
	return &Response{
		body:        body,
		statusCode:  400,
		contentType: "application/json",
	}
}

// GetUsersSelfJSON200Response is a constructor method for a GetUsersSelf response.
// A *Response is returned with the configured status code and content type from the spec.
func GetUsersSelfJSON200Response(body Self) *Response {
	return &Response{
		body:        body,
		statusCode:  200,
		contentType: "application/json",
	}
}

// GetUsersIDJSON200Response is a constructor method for a GetUsersID response.
// A *Response is returned with the configured status code and content type from the spec.
func GetUsersIDJSON200Response(body User) *Response {
	return &Response{
		body:        body,
		statusCode:  200,
		contentType: "application/json",
	}
}

// Getter for additional properties for FoodPreferences_Prefers. Returns the specified
// element and whether it was found
func (a FoodPreferences_Prefers) Get(fieldName string) (value []string, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for FoodPreferences_Prefers
func (a *FoodPreferences_Prefers) Set(fieldName string, value []string) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string][]string)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for FoodPreferences_Prefers to handle AdditionalProperties
func (a *FoodPreferences_Prefers) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string][]string)
		for fieldName, fieldBuf := range object {
			var fieldVal []string
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for FoodPreferences_Prefers to handle AdditionalProperties
func (a FoodPreferences_Prefers) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for UserLikedPosts_Posts. Returns the specified
// element and whether it was found
func (a UserLikedPosts_Posts) Get(fieldName string) (value time.Time, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for UserLikedPosts_Posts
func (a *UserLikedPosts_Posts) Set(fieldName string, value time.Time) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]time.Time)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for UserLikedPosts_Posts to handle AdditionalProperties
func (a *UserLikedPosts_Posts) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]time.Time)
		for fieldName, fieldBuf := range object {
			var fieldVal time.Time
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for UserLikedPosts_Posts to handle AdditionalProperties
func (a UserLikedPosts_Posts) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYXW/buBL9KwRvH+69kD9jO66A+5DepGkW6TbIR5ttGgS0OJKYUKRKUnHdwP99QVKy",
	"LUtN0t1gsQ/7ZIkiD2fmnOEM/YAjmeVSgDAahw9Ygc6l0OBeRpeX9ieSwoAw9pHkOWcRMUyK3q2Wwo7p",
	"KIWM2KdXCmIc4n/11pg9/1X3DpSSCi+XywBT0JFiuQXBIb7QoBCUX4MSzW3vl4QPWwvcMJKzW4gMUmAK",
	"JYAiKRARixIowPCNZDkHHGIN6h4UmnGYoyLHAc6VzEEZ5n3MQGuSgH00i9wtMIqJxBmj4GvBFFAcXq0m",
	"Xi8D/FZKeqIgBgUi8jh1VM7u/MPKjit8yiLAAX7LdIqvA8wMZLpl26AaIEqRhX3P3U5uLqGU2TAQflLb",
	"b7XNg8cPr/BeytB5IQgO8BnhmRR2U2dDeIXPCp0y5N6sP8+3pXz30W/EyLu9tthiH+03KTwTch5zcgfo",
	"aL9G1uvxzrT/ejwYT4aD8XB3PBniYMuoAH/rJLJTDjJhJiNr2LFMmHgPhlBiSHPHD7kPG8rKKYiJiBfU",
	"K4fbxQ1pFBrUDUlK6dfxzlNAVrmdPfsdFRooiqWySAkTCXJwa7+iQvHebncy6g4aDrmcOJHaNGUUyXtQ",
	"NymxjG6QjI8P3n2ciE9vhou7ab6QvxB6+t/u7t3/31Nx28TfyrhNIK8MpCTnzvxX0+4X8UWcKDBmgaIU",
	"SO7GM+i24TL6VNof7bt5GUka+bDI4c2BlrP7SE3mt4ffM3YSnRM43L1JLuKD8aL47c1OSm6Ks2P9v59L",
	"GC79EdWk7bj8gphGJgVUzUTzFBS4oVxqg+ZEo4zQdq8NSbZ9KTMsqCXWz5jstPa8cG7lHKN4vXwV6jrn",
	"pc02Hc+Ax+4k4fxDjMOrx/ezEsfLYFuXM6ZMSsnCPsdSZcTgEFNioEXcdWtXK6+X3hqtS6LyrQMtZ6qJ",
	"3zEsgzZOso3Mf8yh+jFhiZB3sJUUn/j9ySX9tVjExvApnH2c7KZ3M305HsyPL06/n7ft/8f5W1PnTQkq",
	"3218XPwbwSH3xBBVN/qnsqnFgRmTdcB3wLkM0FwqTv9U8guSQR06lpJ2DBMUVMe6/6RqXHgcTlA5X0Xn",
	"mN0Btaen/oGI/ONWC+E/VKeAFRUyKTHuTREDiLOMGVDo33bkFDLChD3WYwac/gcpyDkIplPQNjTPk2he",
	"GfmjIv48mLonznOUkVz7g+toXyMjW7yycUa2PjsyN/oFX3JHO9PhzmQy3O0PRjjEw/5g2ulPO8PR+WAU",
	"DsbhaPoZB23luWXucPi5pVWwjJZhbBKyjnBJiSiyGSgkY2ezRoRzOQeKZou1N4UwjLvXik/rsjYky2s+",
	"7qxs8agNeXlmNg0MVtq5duWZidilh2HGKfhDDmLv5Ah5pbsSaXvCzrkTNQ7wPSh/sOF+t98dWPdlDoLk",
	"DId4p9vv9m27QUzqmO/5BsQKuOwDrC5cZTqirmyV/QlRJAPjmsGrB2yX4K8FqEWVHqE7TspMWbtoVAHB",
	"RqPeEJU2izIzVebO+zbonGg9l4o+Cr0S8cbsJ7a7DurXjmG//2LXjqrAtFw8jmWSAEVMIF1EEWgdF5y7",
	"YjzyBrThrgzt2cuRu7AUWUZsqbKAFq3QVscVD4gIilaxsAt6ChKmTXmwt/J9Ws34h/IXpbyKK9CX4rxC",
	"fJp1+0n3dNl+JVCnHYd2yDVnwZYYDsHYQqfLj21xe77xwUvFmMc2wPVgHIKvNVGhVHkrst2jv7BljFIO",
	"c+IK8hXOCm32CpNKxb77S2gZoQdGlz+O0IVvF9oj5C6TWwnTvLYd7duyUlUR2zILp12TrnXPHlf80y3e",
	"3yKdyv9v/jpZ+OtCmyyIL9m+fDOFfGv4HGEsl78HAAD//5zaK/ykEgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
