// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/discord-gophers/goapi-gen version (devel) DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"encoding/xml"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	openapi_types "github.com/discord-gophers/goapi-gen/pkg/types"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/render"
)

// Error object returned on any error
type Error struct {
	Message string `json:"message"`
}

// FoodPreferences defines model for FoodPreferences.
type FoodPreferences struct {
	Likes   []string                `json:"likes"`
	Prefers FoodPreferences_Prefers `json:"prefers"`
}

// FoodPreferences_Prefers defines model for FoodPreferences.Prefers.
type FoodPreferences_Prefers struct {
	AdditionalProperties map[string][]string `json:"-"`
}

// Snowflake ID
type ID int64

// Optional metadata included on login
type LoginMetadata struct {
	// The User-Agent used for logging in
	UserAgent *string `json:"user_agent,omitempty"`
}

// Post defines model for Post.
type Post struct {
	CoverHash   *string `json:"cover_hash,omitempty"`
	Description string  `json:"description"`

	// Snowflake ID
	ID     ID       `json:"id"`
	Images []string `json:"images"`

	// Location is the location where the post was made.
	Location *string  `json:"location,omitempty"`
	Tags     []string `json:"tags"`

	// Snowflake ID
	UserID ID `json:"user_id"`
}

// Self defines model for Self.
type Self struct {
	// Embedded struct due to allOf(#/components/schemas/User)
	User `yaml:",inline"`
	// Embedded fields due to inline allOf schema
	Birthday openapi_types.Date `json:"birthday"`
}

// Session defines model for Session.
type Session struct {
	Expiry time.Time `json:"expiry"`

	// Optional metadata included on login
	Metadata *LoginMetadata `json:"metadata,omitempty"`
	Token    string         `json:"token"`

	// Snowflake ID
	UserID ID `json:"user_id"`
}

// User defines model for User.
type User struct {
	Avatar string  `json:"avatar"`
	Bio    *string `json:"bio,omitempty"`

	// Snowflake ID
	ID   ID     `json:"id"`
	Name string `json:"name"`
}

// UserLikedPosts defines model for UserLikedPosts.
type UserLikedPosts struct {
	// Expires is the time that the rate limiter (the Remaining field) replenishes.
	Expires time.Time `json:"expires"`

	// Posts maps post IDs to the time that the user liked.
	Posts UserLikedPosts_Posts `json:"posts"`

	// Remaining is the number of likes allowed by the user until the Expires timestamp.
	Remaining float32 `json:"remaining"`
}

// Posts maps post IDs to the time that the user liked.
type UserLikedPosts_Posts struct {
	AdditionalProperties map[string]time.Time `json:"-"`
}

// Error object returned on any error
type N4xX Error

// LoginParams defines parameters for Login.
type LoginParams struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

// RegisterParams defines parameters for Register.
type RegisterParams struct {
	Username string `json:"username"`
}

// GetUsersIDParams defines parameters for GetUsersID.
type GetUsersIDParams struct {
	Password string `json:"password"`
}

// Response is a common response struct for all the API calls.
// A Response object may be instantiated via functions for specific operation responses.
type Response struct {
	body        interface{}
	statusCode  int
	contentType string
}

// Render implements the render.Renderer interface. It sets the Content-Type header
// and status code based on the response definition.
func (resp *Response) Render(w http.ResponseWriter, r *http.Request) error {
	w.Header().Set("Content-Type", resp.contentType)
	render.Status(r, resp.statusCode)
	return nil
}

// Status is a builder method to override the default status code for a response.
func (resp *Response) Status(statusCode int) *Response {
	resp.statusCode = statusCode
	return resp
}

// ContentType is a builder method to override the default content type for a response.
func (resp *Response) ContentType(contentType string) *Response {
	resp.contentType = contentType
	return resp
}

// MarshalJSON implements the json.Marshaler interface.
// This is used to only marshal the body of the response.
func (resp *Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(resp.body)
}

// MarshalXML implements the xml.Marshaler interface.
// This is used to only marshal the body of the response.
func (resp *Response) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return e.Encode(resp.body)
}

// LoginJSON200Response is a constructor method for a Login response.
// A *Response is returned with the configured status code and content type from the spec.
func LoginJSON200Response(body Session) *Response {
	return &Response{
		body:        body,
		statusCode:  200,
		contentType: "application/json",
	}
}

// LoginJSON400Response is a constructor method for a Login response.
// A *Response is returned with the configured status code and content type from the spec.
func LoginJSON400Response(body Error) *Response {
	return &Response{
		body:        body,
		statusCode:  400,
		contentType: "application/json",
	}
}

// RegisterJSON200Response is a constructor method for a Register response.
// A *Response is returned with the configured status code and content type from the spec.
func RegisterJSON200Response(body Session) *Response {
	return &Response{
		body:        body,
		statusCode:  200,
		contentType: "application/json",
	}
}

// RegisterJSON400Response is a constructor method for a Register response.
// A *Response is returned with the configured status code and content type from the spec.
func RegisterJSON400Response(body Error) *Response {
	return &Response{
		body:        body,
		statusCode:  400,
		contentType: "application/json",
	}
}

// GetUsersSelfJSON200Response is a constructor method for a GetUsersSelf response.
// A *Response is returned with the configured status code and content type from the spec.
func GetUsersSelfJSON200Response(body Self) *Response {
	return &Response{
		body:        body,
		statusCode:  200,
		contentType: "application/json",
	}
}

// GetUsersIDJSON200Response is a constructor method for a GetUsersID response.
// A *Response is returned with the configured status code and content type from the spec.
func GetUsersIDJSON200Response(body User) *Response {
	return &Response{
		body:        body,
		statusCode:  200,
		contentType: "application/json",
	}
}

// Getter for additional properties for FoodPreferences_Prefers. Returns the specified
// element and whether it was found
func (a FoodPreferences_Prefers) Get(fieldName string) (value []string, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for FoodPreferences_Prefers
func (a *FoodPreferences_Prefers) Set(fieldName string, value []string) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string][]string)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for FoodPreferences_Prefers to handle AdditionalProperties
func (a *FoodPreferences_Prefers) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string][]string)
		for fieldName, fieldBuf := range object {
			var fieldVal []string
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for FoodPreferences_Prefers to handle AdditionalProperties
func (a FoodPreferences_Prefers) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for UserLikedPosts_Posts. Returns the specified
// element and whether it was found
func (a UserLikedPosts_Posts) Get(fieldName string) (value time.Time, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for UserLikedPosts_Posts
func (a *UserLikedPosts_Posts) Set(fieldName string, value time.Time) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]time.Time)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for UserLikedPosts_Posts to handle AdditionalProperties
func (a *UserLikedPosts_Posts) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]time.Time)
		for fieldName, fieldBuf := range object {
			var fieldVal time.Time
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for UserLikedPosts_Posts to handle AdditionalProperties
func (a UserLikedPosts_Posts) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xYbW/bOBL+KwSvH+4O8mtsxxVwH9ImTXNIt0Fe2mzTIKDFkcWYIlWSsusG/u8LkpJt",
	"WWqS7hbd/RSZL8OZ53k4M8wDjmSaSQHCaBw+YAU6k0KD+zG4vrZ/IikMCGM/SZZxFhHDpOjcaynsmI4S",
	"SIn9eqEgxiH+V2djs+NndedIKanwarUKMAUdKZZZIzjEVxoUgmI2KKy54/2W8GFngxtGcnIPkUEKTK4E",
	"UCQFImJZGAowfCVpxsHuTkFrMgUcYg1qDgpNOCxQnuFVgDMlM1CG+XjXKx+wWWZuh1FMTJ1jCr7kTAHF",
	"4c164e0qwG+kpGcKYlAgIm+napWzmf9Y+3SDz1kEOMBvmE7wbYCZgVQ3HBuUA0QpsvQO25PcWkIps5AQ",
	"flY57/nGtkBynoQ3+CBh6DIXBAf4gvBUCuue8za8wRe5Thhyv2435jwTNYx82BuP7Y6TwzqdF0IuYk5m",
	"gE4Ot4nDL4d74+7LYW846veG/f3hqI+DnZgC/LU1la1ikAkzGti4TuWUiXdgCCWG1E98n3nYUFosQUxE",
	"PKdeRdxuxrvSyDWoOzItrkHV3mUCyKq4dWDnUa6Bolgqa2nKxBQ5c5u4olzxzn57NGj3agG5+3EmtanL",
	"KJJzUHcJsTxtaQmfHr39MBIfX/WXs3G2lP8n9Py/7f3Z63dU3Nft79y+bUOeb6Qk5879F+P2Z/FZnCkw",
	"ZomiBEjmxlNoN9ll9KkUcHLo1qVkWrsPywxeHWk5mUdqtLg//pays+iSwPH+3fQqPhou899f7SXkLr84",
	"1f/7sQvDpU9XddpOixnENDIJoHIlWiSgwA1lUhu0IBqlhLqoN2i9yTkHZaQI0OuDJjwMme5GWdyooHKR",
	"fiQYp8LnAb1zGxnFm+1rEqpqKHy2F/UCeOxyDOfvYxzePH6eFT9eBbuKnTBlEkqW9juWKiUGh5gSAw2y",
	"r3q73nm78t5oXVBYPQG+ZkzV7bcMS6GJk3QrJzwWUDWBWCLkDHauy0c+P7umv+XL2Bg+hosPo/1kNtHX",
	"w97i9Or822XT+X+evw113pWgjN3i4/CvgUPmxBBVdfqH7llDABMmqwbfAucyQAupOP1LaUGQFKqmYylp",
	"yzBBQbVs+E+qxsHj7ARl8CU6p2wG1OZV/R0R+c+dRsNPlPnBigqZhBj3SxEDiLOUGVDo33bkHFLChE34",
	"MQNO/4MUZBwE0wloC83zJJqVTn6vvD/PTDUSFzlKSaZ9Sjs51MjIhqgszshWbtquNlG+GA/2xv290ai/",
	"3+0NcIj73d641R23+oPL3iDsDcPB+BMOmgp3w9p+/xOuNxGW0QLGOiEbhAtKRJ5OQCEZO581IpzLBVA0",
	"WW6iyYVh3P0s+bQha0PSrBLj3toXb7UmL8/MtoPBWju3rnAzEbvrYZhxCn6fgTg4O0Fe6a542m6xdelE",
	"jQM8B+UTG+62u+2eDV9mIEjGcIj32t121zYixCSO+Y5vTayAiw7B6sLVrBPqClrRuRBFUjCuTbx5wHYL",
	"/pKDWpbXI3TppLgpmxCNyiHYaudrotJmWdxMlbp832Q6I1ovpKKPml6LeGv1E8fdBtXHSb/b/WmPk7LA",
	"NDxPTuV0ChQxgXQeRaB1nHPuivHAO9Bkd+1oxz6h3LMmT1NiS5U1aK3l2uq45AERQdEaC7uho2DKtCkS",
	"eyPf5+WKX0b538RBGSjQn0VCafFpGuyU7uiiH5pClQcc2iHXLQU77ByDsZVHF5NNuD3f+eBnYcxjC3AV",
	"jGPwyT/KlSoeMLad82+rlFHKYUFchbzBaa7NQW4Sqdg3/wosEHpgdPV9hK58/W5GyL37dhRcf2GdHNo8",
	"X6Z128MKlz9MstE4ezzrPN1z/SNSWvFvl18nC9+/N8mC+Brq6ylTyPdqzxGGNeX+3dLE5wdf91AX2fJY",
	"cJgrjkOcGJPpsNN5SKQ2Fv9Vh2SsM7eVcE4UIxPuwSrnfZsQk5xb8O0jjtspHDRoiEpbuksd2bMnJJqB",
	"oMj7akG4Xf0RAAD//xaEhEwUEwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
