// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/discord-gophers/goapi-gen version (devel) DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"encoding/xml"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/acmCSUFDev/Food-Tinder/backend/foodtinder"
	"github.com/discord-gophers/goapi-gen/pkg/runtime"
	openapi_types "github.com/discord-gophers/goapi-gen/pkg/types"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/go-chi/render"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Error object returned on any error.
type Error struct {
	Message string `json:"message"`
}

// FoodCategories defines model for FoodCategories.
type FoodCategories struct {
	AdditionalProperties map[string][]string `json:"-"`
}

// FoodPreferences defines model for FoodPreferences.
type FoodPreferences struct {
	Likes   []string       `json:"likes"`
	Prefers FoodCategories `json:"prefers"`
}

// FormError defines model for FormError.
type FormError struct {
	// Embedded struct due to allOf(#/components/schemas/Error)
	Error `yaml:",inline"`
	// Embedded fields due to inline allOf schema
	FormID string `json:"form_id,omitempty"`
}

// Snowflake ID.
type ID foodtinder.ID

// Optional metadata included on login.
type LoginMetadata struct {
	// The User-Agent used for logging in.
	UserAgent string `json:"user_agent,omitempty"`
}

// Post defines model for Post.
type Post struct {
	CoverHash   string `json:"cover_hash,omitempty"`
	Description string `json:"description"`

	// Snowflake ID.
	ID     ID       `json:"id"`
	Images []string `json:"images"`

	// Likes is the number of likes of this post.
	Likes int `json:"likes"`

	// Location is the location where the post was made.
	Location string   `json:"location,omitempty"`
	Tags     []string `json:"tags"`
	Username string   `json:"username"`
}

// PostListing defines model for PostListing.
type PostListing struct {
	// Embedded struct due to allOf(#/components/schemas/Post)
	Post `yaml:",inline"`
	// Embedded fields due to inline allOf schema
	Liked bool `json:"liked"`
}

// Self defines model for Self.
type Self struct {
	// Embedded struct due to allOf(#/components/schemas/User)
	User `yaml:",inline"`
	// Embedded struct due to allOf(#/components/schemas/FoodPreferences)
	FoodPreferences `yaml:",inline"`
	// Embedded fields due to inline allOf schema
	Birthday *openapi_types.Date `json:"birthday,omitempty"`
}

// Session defines model for Session.
type Session struct {
	Expiry time.Time `json:"expiry"`

	// Optional metadata included on login.
	Metadata LoginMetadata `json:"metadata"`
	Token    string        `json:"token"`
	Username string        `json:"username"`
}

// User defines model for User.
type User struct {
	Avatar      string `json:"avatar"`
	Bio         string `json:"bio,omitempty"`
	DisplayName string `json:"display_name,omitempty"`
	Username    string `json:"username"`
}

// Error object returned on a form error.
type NotFoundError FormError

// Error object returned on any error.
type ServerError Error

// Error object returned on any error.
type UserError Error

// LoginParams defines parameters for Login.
type LoginParams struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

// GetNextPostsParams defines parameters for GetNextPosts.
type GetNextPostsParams struct {
	// The ID to start the pagination from, or empty to start from top.
	PrevID *ID `json:"prev_id,omitempty"`
}

// CreatePostJSONBody defines parameters for CreatePost.
type CreatePostJSONBody Post

// LikePostJSONBody defines parameters for LikePost.
type LikePostJSONBody struct {
	Like *bool `json:"like,omitempty"`
}

// RegisterParams defines parameters for Register.
type RegisterParams struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

// CreatePostJSONRequestBody defines body for CreatePost for application/json ContentType.
type CreatePostJSONRequestBody CreatePostJSONBody

// Bind implements render.Binder.
func (CreatePostJSONRequestBody) Bind(*http.Request) error {
	return nil
}

// LikePostJSONRequestBody defines body for LikePost for application/json ContentType.
type LikePostJSONRequestBody LikePostJSONBody

// Bind implements render.Binder.
func (LikePostJSONRequestBody) Bind(*http.Request) error {
	return nil
}

// Response is a common response struct for all the API calls.
// A Response object may be instantiated via functions for specific operation responses.
type Response struct {
	body        interface{}
	statusCode  int
	contentType string
}

// Render implements the render.Renderer interface. It sets the Content-Type header
// and status code based on the response definition.
func (resp *Response) Render(w http.ResponseWriter, r *http.Request) error {
	w.Header().Set("Content-Type", resp.contentType)
	render.Status(r, resp.statusCode)
	return nil
}

// Status is a builder method to override the default status code for a response.
func (resp *Response) Status(statusCode int) *Response {
	resp.statusCode = statusCode
	return resp
}

// ContentType is a builder method to override the default content type for a response.
func (resp *Response) ContentType(contentType string) *Response {
	resp.contentType = contentType
	return resp
}

// MarshalJSON implements the json.Marshaler interface.
// This is used to only marshal the body of the response.
func (resp *Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(resp.body)
}

// MarshalXML implements the xml.Marshaler interface.
// This is used to only marshal the body of the response.
func (resp *Response) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return e.Encode(resp.body)
}

// UploadAssetJSON200Response is a constructor method for a UploadAsset response.
// A *Response is returned with the configured status code and content type from the spec.
func UploadAssetJSON200Response(body string) *Response {
	return &Response{
		body:        body,
		statusCode:  200,
		contentType: "application/json",
	}
}

// UploadAssetJSON400Response is a constructor method for a UploadAsset response.
// A *Response is returned with the configured status code and content type from the spec.
func UploadAssetJSON400Response(body Error) *Response {
	return &Response{
		body:        body,
		statusCode:  400,
		contentType: "application/json",
	}
}

// UploadAssetJSON413Response is a constructor method for a UploadAsset response.
// A *Response is returned with the configured status code and content type from the spec.
func UploadAssetJSON413Response(body Error) *Response {
	return &Response{
		body:        body,
		statusCode:  413,
		contentType: "application/json",
	}
}

// UploadAssetJSON500Response is a constructor method for a UploadAsset response.
// A *Response is returned with the configured status code and content type from the spec.
func UploadAssetJSON500Response(body Error) *Response {
	return &Response{
		body:        body,
		statusCode:  500,
		contentType: "application/json",
	}
}

// GetAssetJSON404Response is a constructor method for a GetAsset response.
// A *Response is returned with the configured status code and content type from the spec.
func GetAssetJSON404Response(body FormError) *Response {
	return &Response{
		body:        body,
		statusCode:  404,
		contentType: "application/json",
	}
}

// GetAssetJSON500Response is a constructor method for a GetAsset response.
// A *Response is returned with the configured status code and content type from the spec.
func GetAssetJSON500Response(body Error) *Response {
	return &Response{
		body:        body,
		statusCode:  500,
		contentType: "application/json",
	}
}

// ListFoodsJSON200Response is a constructor method for a ListFoods response.
// A *Response is returned with the configured status code and content type from the spec.
func ListFoodsJSON200Response(body FoodCategories) *Response {
	return &Response{
		body:        body,
		statusCode:  200,
		contentType: "application/json",
	}
}

// ListFoodsJSON500Response is a constructor method for a ListFoods response.
// A *Response is returned with the configured status code and content type from the spec.
func ListFoodsJSON500Response(body Error) *Response {
	return &Response{
		body:        body,
		statusCode:  500,
		contentType: "application/json",
	}
}

// LoginJSON200Response is a constructor method for a Login response.
// A *Response is returned with the configured status code and content type from the spec.
func LoginJSON200Response(body Session) *Response {
	return &Response{
		body:        body,
		statusCode:  200,
		contentType: "application/json",
	}
}

// LoginJSON401Response is a constructor method for a Login response.
// A *Response is returned with the configured status code and content type from the spec.
func LoginJSON401Response(body Error) *Response {
	return &Response{
		body:        body,
		statusCode:  401,
		contentType: "application/json",
	}
}

// LoginJSON500Response is a constructor method for a Login response.
// A *Response is returned with the configured status code and content type from the spec.
func LoginJSON500Response(body Error) *Response {
	return &Response{
		body:        body,
		statusCode:  500,
		contentType: "application/json",
	}
}

// GetNextPostsJSON200Response is a constructor method for a GetNextPosts response.
// A *Response is returned with the configured status code and content type from the spec.
func GetNextPostsJSON200Response(body []PostListing) *Response {
	return &Response{
		body:        body,
		statusCode:  200,
		contentType: "application/json",
	}
}

// GetNextPostsJSON400Response is a constructor method for a GetNextPosts response.
// A *Response is returned with the configured status code and content type from the spec.
func GetNextPostsJSON400Response(body FormError) *Response {
	return &Response{
		body:        body,
		statusCode:  400,
		contentType: "application/json",
	}
}

// GetNextPostsJSON500Response is a constructor method for a GetNextPosts response.
// A *Response is returned with the configured status code and content type from the spec.
func GetNextPostsJSON500Response(body Error) *Response {
	return &Response{
		body:        body,
		statusCode:  500,
		contentType: "application/json",
	}
}

// CreatePostJSON200Response is a constructor method for a CreatePost response.
// A *Response is returned with the configured status code and content type from the spec.
func CreatePostJSON200Response(body Post) *Response {
	return &Response{
		body:        body,
		statusCode:  200,
		contentType: "application/json",
	}
}

// CreatePostJSON400Response is a constructor method for a CreatePost response.
// A *Response is returned with the configured status code and content type from the spec.
func CreatePostJSON400Response(body Error) *Response {
	return &Response{
		body:        body,
		statusCode:  400,
		contentType: "application/json",
	}
}

// CreatePostJSON500Response is a constructor method for a CreatePost response.
// A *Response is returned with the configured status code and content type from the spec.
func CreatePostJSON500Response(body Error) *Response {
	return &Response{
		body:        body,
		statusCode:  500,
		contentType: "application/json",
	}
}

// GetLikedPostsJSON200Response is a constructor method for a GetLikedPosts response.
// A *Response is returned with the configured status code and content type from the spec.
func GetLikedPostsJSON200Response(body []Post) *Response {
	return &Response{
		body:        body,
		statusCode:  200,
		contentType: "application/json",
	}
}

// GetLikedPostsJSON500Response is a constructor method for a GetLikedPosts response.
// A *Response is returned with the configured status code and content type from the spec.
func GetLikedPostsJSON500Response(body Error) *Response {
	return &Response{
		body:        body,
		statusCode:  500,
		contentType: "application/json",
	}
}

// DeletePostJSON404Response is a constructor method for a DeletePost response.
// A *Response is returned with the configured status code and content type from the spec.
func DeletePostJSON404Response(body FormError) *Response {
	return &Response{
		body:        body,
		statusCode:  404,
		contentType: "application/json",
	}
}

// DeletePostJSON500Response is a constructor method for a DeletePost response.
// A *Response is returned with the configured status code and content type from the spec.
func DeletePostJSON500Response(body Error) *Response {
	return &Response{
		body:        body,
		statusCode:  500,
		contentType: "application/json",
	}
}

// GetPostJSON200Response is a constructor method for a GetPost response.
// A *Response is returned with the configured status code and content type from the spec.
func GetPostJSON200Response(body PostListing) *Response {
	return &Response{
		body:        body,
		statusCode:  200,
		contentType: "application/json",
	}
}

// GetPostJSON404Response is a constructor method for a GetPost response.
// A *Response is returned with the configured status code and content type from the spec.
func GetPostJSON404Response(body FormError) *Response {
	return &Response{
		body:        body,
		statusCode:  404,
		contentType: "application/json",
	}
}

// GetPostJSON500Response is a constructor method for a GetPost response.
// A *Response is returned with the configured status code and content type from the spec.
func GetPostJSON500Response(body Error) *Response {
	return &Response{
		body:        body,
		statusCode:  500,
		contentType: "application/json",
	}
}

// LikePostJSON400Response is a constructor method for a LikePost response.
// A *Response is returned with the configured status code and content type from the spec.
func LikePostJSON400Response(body Error) *Response {
	return &Response{
		body:        body,
		statusCode:  400,
		contentType: "application/json",
	}
}

// LikePostJSON404Response is a constructor method for a LikePost response.
// A *Response is returned with the configured status code and content type from the spec.
func LikePostJSON404Response(body FormError) *Response {
	return &Response{
		body:        body,
		statusCode:  404,
		contentType: "application/json",
	}
}

// LikePostJSON500Response is a constructor method for a LikePost response.
// A *Response is returned with the configured status code and content type from the spec.
func LikePostJSON500Response(body Error) *Response {
	return &Response{
		body:        body,
		statusCode:  500,
		contentType: "application/json",
	}
}

// RegisterJSON200Response is a constructor method for a Register response.
// A *Response is returned with the configured status code and content type from the spec.
func RegisterJSON200Response(body Session) *Response {
	return &Response{
		body:        body,
		statusCode:  200,
		contentType: "application/json",
	}
}

// RegisterJSON400Response is a constructor method for a Register response.
// A *Response is returned with the configured status code and content type from the spec.
func RegisterJSON400Response(body FormError) *Response {
	return &Response{
		body:        body,
		statusCode:  400,
		contentType: "application/json",
	}
}

// RegisterJSON500Response is a constructor method for a Register response.
// A *Response is returned with the configured status code and content type from the spec.
func RegisterJSON500Response(body Error) *Response {
	return &Response{
		body:        body,
		statusCode:  500,
		contentType: "application/json",
	}
}

// GetSelfJSON200Response is a constructor method for a GetSelf response.
// A *Response is returned with the configured status code and content type from the spec.
func GetSelfJSON200Response(body Self) *Response {
	return &Response{
		body:        body,
		statusCode:  200,
		contentType: "application/json",
	}
}

// GetSelfJSON500Response is a constructor method for a GetSelf response.
// A *Response is returned with the configured status code and content type from the spec.
func GetSelfJSON500Response(body Error) *Response {
	return &Response{
		body:        body,
		statusCode:  500,
		contentType: "application/json",
	}
}

// GetUserJSON200Response is a constructor method for a GetUser response.
// A *Response is returned with the configured status code and content type from the spec.
func GetUserJSON200Response(body User) *Response {
	return &Response{
		body:        body,
		statusCode:  200,
		contentType: "application/json",
	}
}

// GetUserJSON400Response is a constructor method for a GetUser response.
// A *Response is returned with the configured status code and content type from the spec.
func GetUserJSON400Response(body FormError) *Response {
	return &Response{
		body:        body,
		statusCode:  400,
		contentType: "application/json",
	}
}

// GetUserJSON404Response is a constructor method for a GetUser response.
// A *Response is returned with the configured status code and content type from the spec.
func GetUserJSON404Response(body FormError) *Response {
	return &Response{
		body:        body,
		statusCode:  404,
		contentType: "application/json",
	}
}

// GetUserJSON500Response is a constructor method for a GetUser response.
// A *Response is returned with the configured status code and content type from the spec.
func GetUserJSON500Response(body Error) *Response {
	return &Response{
		body:        body,
		statusCode:  500,
		contentType: "application/json",
	}
}

// Getter for additional properties for FoodCategories. Returns the specified
// element and whether it was found
func (a FoodCategories) Get(fieldName string) (value []string, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for FoodCategories
func (a *FoodCategories) Set(fieldName string, value []string) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string][]string)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for FoodCategories to handle AdditionalProperties
func (a *FoodCategories) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string][]string)
		for fieldName, fieldBuf := range object {
			var fieldVal []string
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for FoodCategories to handle AdditionalProperties
func (a FoodCategories) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Upload an asset
	// (POST /assets)
	UploadAsset(w http.ResponseWriter, r *http.Request) *Response
	// Get the file asset by the given ID. Note that assets are not separated by type; the user must assume the type from the context that the asset ID is from.
	// (GET /assets/{id})
	GetAsset(w http.ResponseWriter, r *http.Request, id string) *Response
	// Get the list of all valid food categories and names.
	// (GET /food/list)
	ListFoods(w http.ResponseWriter, r *http.Request) *Response
	// Log in using username and password. A 401 is returned if the information is incorrect.
	// (POST /login)
	Login(w http.ResponseWriter, r *http.Request, params LoginParams) *Response
	// Get the next batch of posts
	// (GET /posts)
	GetNextPosts(w http.ResponseWriter, r *http.Request, params GetNextPostsParams) *Response
	// Create a new post
	// (POST /posts)
	CreatePost(w http.ResponseWriter, r *http.Request) *Response
	// Get the list of posts liked by the user
	// (GET /posts/like)
	GetLikedPosts(w http.ResponseWriter, r *http.Request) *Response
	// Delete the current user's posts by ID. A 401 is returned if the user tries to delete someone else's post.
	// (DELETE /posts/{id})
	DeletePost(w http.ResponseWriter, r *http.Request, id ID) *Response
	// Get the post with the given ID.
	// (GET /posts/{id})
	GetPost(w http.ResponseWriter, r *http.Request, id ID) *Response
	// Like or unlike the post
	// (POST /posts/{id}/like)
	LikePost(w http.ResponseWriter, r *http.Request, id ID) *Response
	// Register using username and password
	// (POST /register)
	Register(w http.ResponseWriter, r *http.Request, params RegisterParams) *Response
	// Get the current user
	// (GET /users/@self)
	GetSelf(w http.ResponseWriter, r *http.Request) *Response
	// Get a user by their username
	// (GET /users/{username})
	GetUser(w http.ResponseWriter, r *http.Request, username string) *Response
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler          ServerInterface
	Middlewares      map[string]func(http.Handler) http.Handler
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// UploadAsset operation middleware
func (siw *ServerInterfaceWrapper) UploadAsset(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.UploadAsset(w, r)
		if resp != nil {
			render.Render(w, r, resp)
		}
	})

	handler(w, r.WithContext(ctx))
}

// GetAsset operation middleware
func (siw *ServerInterfaceWrapper) GetAsset(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "id" -------------
	var id string

	if err := runtime.BindStyledParameter("simple", false, "id", chi.URLParam(r, "id"), &id); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "id"})
		return
	}

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.GetAsset(w, r, id)
		if resp != nil {
			render.Render(w, r, resp)
		}
	})

	handler(w, r.WithContext(ctx))
}

// ListFoods operation middleware
func (siw *ServerInterfaceWrapper) ListFoods(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.ListFoods(w, r)
		if resp != nil {
			render.Render(w, r, resp)
		}
	})

	handler(w, r.WithContext(ctx))
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// Parameter object where we will unmarshal all parameters from the context
	var params LoginParams

	// ------------- Required query parameter "username" -------------

	if err := runtime.BindQueryParameter("form", true, true, "username", r.URL.Query(), &params.Username); err != nil {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{err, "username"})
		return
	}

	// ------------- Required query parameter "password" -------------

	if err := runtime.BindQueryParameter("form", true, true, "password", r.URL.Query(), &params.Password); err != nil {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{err, "password"})
		return
	}

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.Login(w, r, params)
		if resp != nil {
			render.Render(w, r, resp)
		}
	})

	handler(w, r.WithContext(ctx))
}

// GetNextPosts operation middleware
func (siw *ServerInterfaceWrapper) GetNextPosts(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetNextPostsParams

	// ------------- Optional query parameter "prev_id" -------------

	if err := runtime.BindQueryParameter("form", true, false, "prev_id", r.URL.Query(), &params.PrevID); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "prev_id"})
		return
	}

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.GetNextPosts(w, r, params)
		if resp != nil {
			render.Render(w, r, resp)
		}
	})

	handler(w, r.WithContext(ctx))
}

// CreatePost operation middleware
func (siw *ServerInterfaceWrapper) CreatePost(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.CreatePost(w, r)
		if resp != nil {
			render.Render(w, r, resp)
		}
	})

	handler(w, r.WithContext(ctx))
}

// GetLikedPosts operation middleware
func (siw *ServerInterfaceWrapper) GetLikedPosts(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.GetLikedPosts(w, r)
		if resp != nil {
			render.Render(w, r, resp)
		}
	})

	handler(w, r.WithContext(ctx))
}

// DeletePost operation middleware
func (siw *ServerInterfaceWrapper) DeletePost(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "id" -------------
	var id ID

	if err := runtime.BindStyledParameter("simple", false, "id", chi.URLParam(r, "id"), &id); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "id"})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.DeletePost(w, r, id)
		if resp != nil {
			render.Render(w, r, resp)
		}
	})

	handler(w, r.WithContext(ctx))
}

// GetPost operation middleware
func (siw *ServerInterfaceWrapper) GetPost(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "id" -------------
	var id ID

	if err := runtime.BindStyledParameter("simple", false, "id", chi.URLParam(r, "id"), &id); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "id"})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.GetPost(w, r, id)
		if resp != nil {
			render.Render(w, r, resp)
		}
	})

	handler(w, r.WithContext(ctx))
}

// LikePost operation middleware
func (siw *ServerInterfaceWrapper) LikePost(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "id" -------------
	var id ID

	if err := runtime.BindStyledParameter("simple", false, "id", chi.URLParam(r, "id"), &id); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "id"})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.LikePost(w, r, id)
		if resp != nil {
			render.Render(w, r, resp)
		}
	})

	handler(w, r.WithContext(ctx))
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// Parameter object where we will unmarshal all parameters from the context
	var params RegisterParams

	// ------------- Required query parameter "username" -------------

	if err := runtime.BindQueryParameter("form", true, true, "username", r.URL.Query(), &params.Username); err != nil {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{err, "username"})
		return
	}

	// ------------- Required query parameter "password" -------------

	if err := runtime.BindQueryParameter("form", true, true, "password", r.URL.Query(), &params.Password); err != nil {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{err, "password"})
		return
	}

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.Register(w, r, params)
		if resp != nil {
			render.Render(w, r, resp)
		}
	})

	handler(w, r.WithContext(ctx))
}

// GetSelf operation middleware
func (siw *ServerInterfaceWrapper) GetSelf(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.GetSelf(w, r)
		if resp != nil {
			render.Render(w, r, resp)
		}
	})

	handler(w, r.WithContext(ctx))
}

// GetUser operation middleware
func (siw *ServerInterfaceWrapper) GetUser(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "username" -------------
	var username string

	if err := runtime.BindStyledParameter("simple", false, "username", chi.URLParam(r, "username"), &username); err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "username"})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.GetUser(w, r, username)
		if resp != nil {
			render.Render(w, r, resp)
		}
	})

	handler(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	err       error
	paramName string
}

// Error implements error.
func (err UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter %s: %v", err.paramName, err.err)
}

func (err UnescapedCookieParamError) Unwrap() error { return err.err }

type UnmarshalingParamError struct {
	err       error
	paramName string
}

// Error implements error.
func (err UnmarshalingParamError) Error() string {
	return fmt.Sprintf("error unmarshaling parameter %s as JSON: %v", err.paramName, err.err)
}

func (err UnmarshalingParamError) Unwrap() error { return err.err }

type RequiredParamError struct {
	err       error
	paramName string
}

// Error implements error.
func (err RequiredParamError) Error() string {
	if err.err == nil {
		return fmt.Sprintf("query parameter %s is required, but not found", err.paramName)
	} else {
		return fmt.Sprintf("query parameter %s is required, but errored: %s", err.paramName, err.err)
	}
}

func (err RequiredParamError) Unwrap() error { return err.err }

type RequiredHeaderError struct {
	paramName string
}

// Error implements error.
func (err RequiredHeaderError) Error() string {
	return fmt.Sprintf("header parameter %s is required, but not found", err.paramName)
}

type InvalidParamFormatError struct {
	err       error
	paramName string
}

// Error implements error.
func (err InvalidParamFormatError) Error() string {
	return fmt.Sprintf("invalid format for parameter %s: %v", err.paramName, err.err)
}

func (err InvalidParamFormatError) Unwrap() error { return err.err }

type TooManyValuesForParamError struct {
	NumValues int
	paramName string
}

// Error implements error.
func (err TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("expected one value for %s, got %d", err.paramName, err.NumValues)
}

// ParameterName is an interface that is implemented by error types that are
// relevant to a specific parameter.
type ParameterError interface {
	error
	// ParamName is the name of the parameter that the error is referring to.
	ParamName() string
}

func (err UnescapedCookieParamError) ParamName() string  { return err.paramName }
func (err UnmarshalingParamError) ParamName() string     { return err.paramName }
func (err RequiredParamError) ParamName() string         { return err.paramName }
func (err RequiredHeaderError) ParamName() string        { return err.paramName }
func (err InvalidParamFormatError) ParamName() string    { return err.paramName }
func (err TooManyValuesForParamError) ParamName() string { return err.paramName }

type ServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      map[string]func(http.Handler) http.Handler
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

type ServerOption func(*ServerOptions)

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface, opts ...ServerOption) http.Handler {
	options := &ServerOptions{
		BaseURL:     "/",
		BaseRouter:  chi.NewRouter(),
		Middlewares: make(map[string]func(http.Handler) http.Handler),
		ErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
	}

	for _, f := range opts {
		f(options)
	}

	r := options.BaseRouter
	wrapper := ServerInterfaceWrapper{
		Handler:          si,
		Middlewares:      options.Middlewares,
		ErrorHandlerFunc: options.ErrorHandlerFunc,
	}

	r.Route(options.BaseURL, func(r chi.Router) {
		r.Post("/assets", wrapper.UploadAsset)
		r.Get("/assets/{id}", wrapper.GetAsset)
		r.Get("/food/list", wrapper.ListFoods)
		r.Post("/login", wrapper.Login)
		r.Get("/posts", wrapper.GetNextPosts)
		r.Post("/posts", wrapper.CreatePost)
		r.Get("/posts/like", wrapper.GetLikedPosts)
		r.Delete("/posts/{id}", wrapper.DeletePost)
		r.Get("/posts/{id}", wrapper.GetPost)
		r.Post("/posts/{id}/like", wrapper.LikePost)
		r.Post("/register", wrapper.Register)
		r.Get("/users/@self", wrapper.GetSelf)
		r.Get("/users/{username}", wrapper.GetUser)

	})
	return r
}

func WithRouter(r chi.Router) ServerOption {
	return func(s *ServerOptions) {
		s.BaseRouter = r
	}
}

func WithServerBaseURL(url string) ServerOption {
	return func(s *ServerOptions) {
		s.BaseURL = url
	}
}

func WithMiddleware(key string, middleware func(http.Handler) http.Handler) ServerOption {
	return func(s *ServerOptions) {
		s.Middlewares[key] = middleware
	}
}

func WithMiddlewares(middlewares map[string]func(http.Handler) http.Handler) ServerOption {
	return func(s *ServerOptions) {
		s.Middlewares = middlewares
	}
}

func WithErrorHandler(handler func(w http.ResponseWriter, r *http.Request, err error)) ServerOption {
	return func(s *ServerOptions) {
		s.ErrorHandlerFunc = handler
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xa/27bOBJ+FYK3QO8KxXbaJu36cMAl/bU5pG3QtN09dI2AlsYWG4rUkpQdt/C7H4ak",
	"ZMmSHSdNunfA/WdJ1HDmm5lvZih/o7HKciVBWkOH36gGkytpwF28Ujp7qbXSeBEraUFa/MnyXPCYWa5k",
	"/4tREu+ZOIWM4a+fNEzokP6lv5Lc909NfyVxuVxGNAETa56jIDp02xHApz26jOhbZV+pQiY/UIP3YFSh",
	"YyBcJigeEjJeEEZyplkGFjT5K58QJhd/I9zIB5ZMUEGn7TnoGei71XWjnh8lXOUQo37G7VuD7aP5cWqY",
	"2s7LKIhzoVNp0HzD3SZq/AViSzTYQktIiJKIaSkponDFslwAvp6BMWwKdEiDoWMBc1LkaGmuVQ7ach+s",
	"1cpv1C5y94bVXE6dZhr+KLiGhA4/VwtHy4i+Uip5zixMlQ5iWJJwVJaJs4Z4biEzHcKj8gbTmi3wuqb9",
	"K25S3PIo5eRDIRmN6DkTmZJ0FNH3PAZ8eF6YlBN3NVqJ8xjRoOOZhglokLFXpmm54Jf+R7XzZy888gqM",
	"ohton7udzPVp1ABuHWOv0kqax7rGJkyIdxM6/LxT5EXrFk+Uzi540jYoold7U7Wncu/CvRkTBdCh1QUs",
	"l8tRtHM4kkmNjBo+rfamhQEtWYY4r8I048ZwOSXVQ4Tm5EU7Fc6lmk8EuwRy8qKxBf354PGzwc8H+weH",
	"j/YPHj09OHxEo247w82JUonlMgHdO3mBTjxVUy7fgGUJs6y99bsAD8nCEsJlLIrE2y7w5R5dzy806IJN",
	"A5s0BX5IgSAZ7B3hc7Q9QQBR1BTB8PJWFsaFFv2nvcMnvf1Npm1wYUTPlLHtHIjVDPRFyjDfaolAT1/+",
	"8ulQ/nr8aHH5LF+of7Hk/cPe08vnbxL5pbX1OsHVBfm8JVoJ4Uz76Vnvd/m7PNNg7YLEKbDc3c+g1yXX",
	"B+u2WPee4xmbtpJ5kcPxS6PGs1gfzr+8/prxs/gDg9dPL6YfJy8PFsW/jx+n7KI4PzX/uFm2V9TR9Ocp",
	"3ibcEJsCkUU2Bk3UhLjV+MOm3JBcGdtw6/6g2oBLC1PQbgvli07HLuFJuVG5ksxT0OBu4R5kzgzJWALN",
	"GHpVCAHaKhmR50ddkFs2XQcykG/U4Nyb4FVldSM2MP8ufAJe4Iq2Nmv0yBMa1ekjeL0ZfsGC0kmjbYnh",
	"0+KUG4vb7cyvLpfa9Iob1sl1rJQAJjtZPqGj5cj1P2Ky+8ZIFm7j62pMvfC1FR1zbdOELUpeZpYOacIs",
	"dHggaGlMiMWmJLjKuW7L2bM8g67gymrkus2GJhNjRKlLWKOWX8Xs7LfkbbGYWCuewfmnw6fp5dj8drA/",
	"P/34/uuHrv3vKBBrMegVi0okaiaOQlfZRo3NmGW6qcONyKrDsjFXTYG/gBAqInOlRdLJrQk3uWCLizYe",
	"GEHkg8PD1aebIbnnkdy7KZIBla0Ji90yxIXmdnGOoeLxPAamQR8VNq26c5d/7vZKhdTa3PfjXE4cWpZb",
	"p/a7HOTR2Qnx4ecKEmKw5zGgEZ2B9glAB71Bbx8BUDlIlnM6pI97g94ACz+zqdOnz4wBPxjmoeyuTQC5",
	"UCxx3fuECyDMECaJe4swmZApWDJm8aUjc38ba3TftzwYSo7xT5JK1hEuoh5bMPZYJYu1QeZh/2EjT8dc",
	"MhewbQe1uxTX7bgKFvRxM1Nj6n00GNxodGpvImHeNJbYlFnCE5CWTzgYX0DD/h1Uta65A4UUDiCc+Yo4",
	"BmMmhRALp/8Tr3IXEVWm9VeDIb6x//j+50OvtgsMrOFWKTLm0x45scSkqhAJGQPZf3NMsFUEY5wtB7vY",
	"Up+2XS4VWYZBUItID697GsK4/40nS5Q9BWdxM/xegy1jrxr3jStkbQd756JfFZmAjVP0IsenmDo0op5Q",
	"fJ1fsQRmflQDdd3vo2sjMcT+SsT1WbB08fHkekyb5y239kRgNTr8PKr75TVYl3SBJhC/8cLdmfIZSByC",
	"yFtlwaeKdxhhGohUlhhAl4TjGDTw7+5N5FySFcatLzLfMuJjMtEqc1cOuyvrpdq667hxq/zJRR/5vi+4",
	"57jO+MDmCrnU0O/kixuN1cv78gPaikTIhCAzJjgObCohcbW542+MYxMgcnNhvRSs4eMet5LHZcUfBbjY",
	"DGlRq5U7J0dEjV2E0qwz1wt2ic6ZMXOlt+ddlTS11ddsN7pHp5dNaQeDnqrpFBLCZRfn798/gz8Z7JOP",
	"khU2VZp/hWR1SDJPQa6SECQ63F3Ptaodf7goKmEmscqQp1B4784Z5lRNEaiicfzS2L9HjghaxM3KDu57",
	"AWykMCjCOMplrLSG2IbYx5A320rHW7iyZ27RDuXDFw5jmfa5mLNpQMVRUoT1ELLcLlbLPKGpvCo063Gv",
	"YXbhys1uHj95sVO92R5S1dx83YxZDqatiTpUpx2ioHZu/909QsmBEivDmNk4RSb0Pl5GG1rd5xqYBcJc",
	"d+fOJTC0fBwFaXOxILFbloSTC25TbEW62l0vz03g27rd2ye1H+6vb4NLe76/E95Fm1t1q9/p75braknd",
	"F/wStmX2Kb+EpEztH5MuG/LkjqK+rPzOfHeml5StmJt0a9iUDXMCAiy04Xnh7ocYvpb2XEp47vMCb9c1",
	"35bW1mYTIQIC9coaFEtChf1xXXPlJQ+p710LrcNxun5ggrbjhWuVNxYyV46ta+AqnIlRGSgJBISBB2aV",
	"7Zti/n/Eo3dGTFV9+uHTUis7V3WjMRutZ2VFWxuacX7535mWtytz7ePpztPpbcUOOymw2LbaFDR2WDhY",
	"VojzwIS9lo3LXdgEsQ5UqjQppP95F+c0f0YsYvSs7KhA8jGoYcqNDafBncH3vlzx/2HwTofBEtdbR9Yd",
	"9NAbZq9StW3Tlw8ffGT6/zThc9GmCuQ+J90rzGJyt21VvVrXTf1WgrH16DF8nbiWrCtk1arcb+DrnRLr",
	"Rt+O7jPu/RfBW86Df1rFZr7f8u0z1/V/fTSzpflt5/MIsfT/aOry9Cf/lYYMyNHZCUG3oo8LLeiQ9lnO",
	"+7MBXY6W/wkAAP//UKwGKL0nAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
