// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/discord-gophers/goapi-gen version (devel) DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"encoding/xml"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/acmCSUFDev/Food-Tinder/backend/foodtinder"
	"github.com/discord-gophers/goapi-gen/pkg/runtime"
	openapi_types "github.com/discord-gophers/goapi-gen/pkg/types"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/go-chi/render"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Error object returned on any error.
type Error struct {
	Message string `json:"message"`
}

// FoodPreferences defines model for FoodPreferences.
type FoodPreferences struct {
	Likes   []string                `json:"likes"`
	Prefers FoodPreferences_Prefers `json:"prefers"`
}

// FoodPreferences_Prefers defines model for FoodPreferences.Prefers.
type FoodPreferences_Prefers struct {
	AdditionalProperties map[string][]string `json:"-"`
}

// FormError defines model for FormError.
type FormError struct {
	// Embedded struct due to allOf(#/components/schemas/Error)
	Error `yaml:",inline"`
	// Embedded fields due to inline allOf schema
	FormID *string `json:"form_id,omitempty"`
}

// Snowflake ID.
type ID foodtinder.ID

// Optional metadata included on login.
type LoginMetadata struct {
	// The User-Agent used for logging in.
	UserAgent *string `json:"user_agent,omitempty"`
}

// Post defines model for Post.
type Post struct {
	CoverHash   *string `json:"cover_hash,omitempty"`
	Description string  `json:"description"`

	// Snowflake ID.
	ID     ID       `json:"id"`
	Images []string `json:"images"`

	// Location is the location where the post was made.
	Location *string  `json:"location,omitempty"`
	Tags     []string `json:"tags"`

	// Snowflake ID.
	UserID ID `json:"user_id"`
}

// Self defines model for Self.
type Self struct {
	// Embedded struct due to allOf(#/components/schemas/User)
	User `yaml:",inline"`
	// Embedded struct due to allOf(#/components/schemas/FoodPreferences)
	FoodPreferences `yaml:",inline"`
	// Embedded fields due to inline allOf schema
	Birthday openapi_types.Date `json:"birthday"`
}

// Session defines model for Session.
type Session struct {
	Expiry time.Time `json:"expiry"`

	// Optional metadata included on login.
	Metadata LoginMetadata `json:"metadata"`
	Token    string        `json:"token"`

	// Snowflake ID.
	UserID ID `json:"user_id"`
}

// User defines model for User.
type User struct {
	Avatar string  `json:"avatar"`
	Bio    *string `json:"bio,omitempty"`

	// Snowflake ID.
	ID   ID     `json:"id"`
	Name string `json:"name"`
}

// Error object returned on a form error.
type NotFoundError FormError

// Error object returned on any error.
type ServerError Error

// LoginParams defines parameters for Login.
type LoginParams struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

// GetNextPostsParams defines parameters for GetNextPosts.
type GetNextPostsParams struct {
	// The ID to start the pagination from, or empty to start from top.
	PrevID *ID `json:"prev_id,omitempty"`
}

// RegisterParams defines parameters for Register.
type RegisterParams struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

// GetUserParams defines parameters for GetUser.
type GetUserParams struct {
	Password string `json:"password"`
}

// Response is a common response struct for all the API calls.
// A Response object may be instantiated via functions for specific operation responses.
type Response struct {
	body        interface{}
	statusCode  int
	contentType string
}

// Render implements the render.Renderer interface. It sets the Content-Type header
// and status code based on the response definition.
func (resp *Response) Render(w http.ResponseWriter, r *http.Request) error {
	w.Header().Set("Content-Type", resp.contentType)
	render.Status(r, resp.statusCode)
	return nil
}

// Status is a builder method to override the default status code for a response.
func (resp *Response) Status(statusCode int) *Response {
	resp.statusCode = statusCode
	return resp
}

// ContentType is a builder method to override the default content type for a response.
func (resp *Response) ContentType(contentType string) *Response {
	resp.contentType = contentType
	return resp
}

// MarshalJSON implements the json.Marshaler interface.
// This is used to only marshal the body of the response.
func (resp *Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(resp.body)
}

// MarshalXML implements the xml.Marshaler interface.
// This is used to only marshal the body of the response.
func (resp *Response) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return e.Encode(resp.body)
}

// GetAssetJSON404Response is a constructor method for a GetAsset response.
// A *Response is returned with the configured status code and content type from the spec.
func GetAssetJSON404Response(body FormError) *Response {
	return &Response{
		body:        body,
		statusCode:  404,
		contentType: "application/json",
	}
}

// GetAssetJSON500Response is a constructor method for a GetAsset response.
// A *Response is returned with the configured status code and content type from the spec.
func GetAssetJSON500Response(body Error) *Response {
	return &Response{
		body:        body,
		statusCode:  500,
		contentType: "application/json",
	}
}

// LoginJSON200Response is a constructor method for a Login response.
// A *Response is returned with the configured status code and content type from the spec.
func LoginJSON200Response(body Session) *Response {
	return &Response{
		body:        body,
		statusCode:  200,
		contentType: "application/json",
	}
}

// LoginJSON401Response is a constructor method for a Login response.
// A *Response is returned with the configured status code and content type from the spec.
func LoginJSON401Response(body Error) *Response {
	return &Response{
		body:        body,
		statusCode:  401,
		contentType: "application/json",
	}
}

// LoginJSON500Response is a constructor method for a Login response.
// A *Response is returned with the configured status code and content type from the spec.
func LoginJSON500Response(body Error) *Response {
	return &Response{
		body:        body,
		statusCode:  500,
		contentType: "application/json",
	}
}

// GetNextPostsJSON200Response is a constructor method for a GetNextPosts response.
// A *Response is returned with the configured status code and content type from the spec.
func GetNextPostsJSON200Response(body []Post) *Response {
	return &Response{
		body:        body,
		statusCode:  200,
		contentType: "application/json",
	}
}

// GetNextPostsJSON400Response is a constructor method for a GetNextPosts response.
// A *Response is returned with the configured status code and content type from the spec.
func GetNextPostsJSON400Response(body FormError) *Response {
	return &Response{
		body:        body,
		statusCode:  400,
		contentType: "application/json",
	}
}

// GetNextPostsJSON500Response is a constructor method for a GetNextPosts response.
// A *Response is returned with the configured status code and content type from the spec.
func GetNextPostsJSON500Response(body Error) *Response {
	return &Response{
		body:        body,
		statusCode:  500,
		contentType: "application/json",
	}
}

// GetLikedPostsJSON200Response is a constructor method for a GetLikedPosts response.
// A *Response is returned with the configured status code and content type from the spec.
func GetLikedPostsJSON200Response(body []Post) *Response {
	return &Response{
		body:        body,
		statusCode:  200,
		contentType: "application/json",
	}
}

// GetLikedPostsJSON500Response is a constructor method for a GetLikedPosts response.
// A *Response is returned with the configured status code and content type from the spec.
func GetLikedPostsJSON500Response(body Error) *Response {
	return &Response{
		body:        body,
		statusCode:  500,
		contentType: "application/json",
	}
}

// DeletePostJSON404Response is a constructor method for a DeletePost response.
// A *Response is returned with the configured status code and content type from the spec.
func DeletePostJSON404Response(body FormError) *Response {
	return &Response{
		body:        body,
		statusCode:  404,
		contentType: "application/json",
	}
}

// DeletePostJSON500Response is a constructor method for a DeletePost response.
// A *Response is returned with the configured status code and content type from the spec.
func DeletePostJSON500Response(body Error) *Response {
	return &Response{
		body:        body,
		statusCode:  500,
		contentType: "application/json",
	}
}

// RegisterJSON200Response is a constructor method for a Register response.
// A *Response is returned with the configured status code and content type from the spec.
func RegisterJSON200Response(body Session) *Response {
	return &Response{
		body:        body,
		statusCode:  200,
		contentType: "application/json",
	}
}

// RegisterJSON400Response is a constructor method for a Register response.
// A *Response is returned with the configured status code and content type from the spec.
func RegisterJSON400Response(body FormError) *Response {
	return &Response{
		body:        body,
		statusCode:  400,
		contentType: "application/json",
	}
}

// RegisterJSON500Response is a constructor method for a Register response.
// A *Response is returned with the configured status code and content type from the spec.
func RegisterJSON500Response(body Error) *Response {
	return &Response{
		body:        body,
		statusCode:  500,
		contentType: "application/json",
	}
}

// GetSelfJSON200Response is a constructor method for a GetSelf response.
// A *Response is returned with the configured status code and content type from the spec.
func GetSelfJSON200Response(body Self) *Response {
	return &Response{
		body:        body,
		statusCode:  200,
		contentType: "application/json",
	}
}

// GetSelfJSON500Response is a constructor method for a GetSelf response.
// A *Response is returned with the configured status code and content type from the spec.
func GetSelfJSON500Response(body Error) *Response {
	return &Response{
		body:        body,
		statusCode:  500,
		contentType: "application/json",
	}
}

// GetUserJSON200Response is a constructor method for a GetUser response.
// A *Response is returned with the configured status code and content type from the spec.
func GetUserJSON200Response(body User) *Response {
	return &Response{
		body:        body,
		statusCode:  200,
		contentType: "application/json",
	}
}

// GetUserJSON400Response is a constructor method for a GetUser response.
// A *Response is returned with the configured status code and content type from the spec.
func GetUserJSON400Response(body FormError) *Response {
	return &Response{
		body:        body,
		statusCode:  400,
		contentType: "application/json",
	}
}

// GetUserJSON404Response is a constructor method for a GetUser response.
// A *Response is returned with the configured status code and content type from the spec.
func GetUserJSON404Response(body FormError) *Response {
	return &Response{
		body:        body,
		statusCode:  404,
		contentType: "application/json",
	}
}

// GetUserJSON500Response is a constructor method for a GetUser response.
// A *Response is returned with the configured status code and content type from the spec.
func GetUserJSON500Response(body Error) *Response {
	return &Response{
		body:        body,
		statusCode:  500,
		contentType: "application/json",
	}
}

// Getter for additional properties for FoodPreferences_Prefers. Returns the specified
// element and whether it was found
func (a FoodPreferences_Prefers) Get(fieldName string) (value []string, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for FoodPreferences_Prefers
func (a *FoodPreferences_Prefers) Set(fieldName string, value []string) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string][]string)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for FoodPreferences_Prefers to handle AdditionalProperties
func (a *FoodPreferences_Prefers) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string][]string)
		for fieldName, fieldBuf := range object {
			var fieldVal []string
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for FoodPreferences_Prefers to handle AdditionalProperties
func (a FoodPreferences_Prefers) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get the file asset by the given ID. Note that assets are not separated by type; the user must assume the type from the context that the asset ID is from.
	// (GET /assets/{id})
	GetAsset(w http.ResponseWriter, r *http.Request, id string) *Response
	// Log in using username and password. A 401 is returned if the information is incorrect.
	// (POST /login)
	Login(w http.ResponseWriter, r *http.Request, params LoginParams) *Response
	// Get the next batch of posts
	// (GET /posts)
	GetNextPosts(w http.ResponseWriter, r *http.Request, params GetNextPostsParams) *Response
	// Get the list of posts liked by the user
	// (GET /posts/liked)
	GetLikedPosts(w http.ResponseWriter, r *http.Request) *Response
	// Delete the current user's posts by ID. A 401 is returned if the user tries to delete someone else's post.
	// (DELETE /posts/{id})
	DeletePost(w http.ResponseWriter, r *http.Request, id ID) *Response
	// Register using username and password
	// (POST /register)
	Register(w http.ResponseWriter, r *http.Request, params RegisterParams) *Response
	// Get the current user
	// (GET /users/self)
	GetSelf(w http.ResponseWriter, r *http.Request) *Response
	// Get a user by their ID
	// (GET /users/{id})
	GetUser(w http.ResponseWriter, r *http.Request, id ID, params GetUserParams) *Response
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler          ServerInterface
	Middlewares      map[string]func(http.Handler) http.Handler
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// GetAsset operation middleware
func (siw *ServerInterfaceWrapper) GetAsset(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "id" -------------
	var id string

	if err := runtime.BindStyledParameter("simple", false, "id", chi.URLParam(r, "id"), &id); err != nil {
		err = fmt.Errorf("invalid format for parameter id: %w", err)
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "id"})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.GetAsset(w, r, id)
		if resp != nil {
			render.Render(w, r, resp)
		}
	})

	handler(w, r.WithContext(ctx))
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// Parameter object where we will unmarshal all parameters from the context
	var params LoginParams

	// ------------- Required query parameter "username" -------------

	if err := runtime.BindQueryParameter("form", true, true, "username", r.URL.Query(), &params.Username); err != nil {
		err = fmt.Errorf("invalid format for parameter username: %w", err)
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "username"})
		return
	}

	// ------------- Required query parameter "password" -------------

	if err := runtime.BindQueryParameter("form", true, true, "password", r.URL.Query(), &params.Password); err != nil {
		err = fmt.Errorf("invalid format for parameter password: %w", err)
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "password"})
		return
	}

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.Login(w, r, params)
		if resp != nil {
			render.Render(w, r, resp)
		}
	})

	handler(w, r.WithContext(ctx))
}

// GetNextPosts operation middleware
func (siw *ServerInterfaceWrapper) GetNextPosts(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetNextPostsParams

	// ------------- Optional query parameter "prev_id" -------------

	if err := runtime.BindQueryParameter("form", true, false, "prev_id", r.URL.Query(), &params.PrevID); err != nil {
		err = fmt.Errorf("invalid format for parameter prev_id: %w", err)
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "prev_id"})
		return
	}

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.GetNextPosts(w, r, params)
		if resp != nil {
			render.Render(w, r, resp)
		}
	})

	handler(w, r.WithContext(ctx))
}

// GetLikedPosts operation middleware
func (siw *ServerInterfaceWrapper) GetLikedPosts(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.GetLikedPosts(w, r)
		if resp != nil {
			render.Render(w, r, resp)
		}
	})

	handler(w, r.WithContext(ctx))
}

// DeletePost operation middleware
func (siw *ServerInterfaceWrapper) DeletePost(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "id" -------------
	var id ID

	if err := runtime.BindStyledParameter("simple", false, "id", chi.URLParam(r, "id"), &id); err != nil {
		err = fmt.Errorf("invalid format for parameter id: %w", err)
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "id"})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.DeletePost(w, r, id)
		if resp != nil {
			render.Render(w, r, resp)
		}
	})

	handler(w, r.WithContext(ctx))
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// Parameter object where we will unmarshal all parameters from the context
	var params RegisterParams

	// ------------- Required query parameter "username" -------------

	if err := runtime.BindQueryParameter("form", true, true, "username", r.URL.Query(), &params.Username); err != nil {
		err = fmt.Errorf("invalid format for parameter username: %w", err)
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "username"})
		return
	}

	// ------------- Required query parameter "password" -------------

	if err := runtime.BindQueryParameter("form", true, true, "password", r.URL.Query(), &params.Password); err != nil {
		err = fmt.Errorf("invalid format for parameter password: %w", err)
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "password"})
		return
	}

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.Register(w, r, params)
		if resp != nil {
			render.Render(w, r, resp)
		}
	})

	handler(w, r.WithContext(ctx))
}

// GetSelf operation middleware
func (siw *ServerInterfaceWrapper) GetSelf(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.GetSelf(w, r)
		if resp != nil {
			render.Render(w, r, resp)
		}
	})

	handler(w, r.WithContext(ctx))
}

// GetUser operation middleware
func (siw *ServerInterfaceWrapper) GetUser(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// ------------- Path parameter "id" -------------
	var id ID

	if err := runtime.BindStyledParameter("simple", false, "id", chi.URLParam(r, "id"), &id); err != nil {
		err = fmt.Errorf("invalid format for parameter id: %w", err)
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "id"})
		return
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUserParams

	// ------------- Required query parameter "password" -------------

	if err := runtime.BindQueryParameter("form", true, true, "password", r.URL.Query(), &params.Password); err != nil {
		err = fmt.Errorf("invalid format for parameter password: %w", err)
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{err, "password"})
		return
	}

	var handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := siw.Handler.GetUser(w, r, id, params)
		if resp != nil {
			render.Render(w, r, resp)
		}
	})

	handler(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	error
}

type UnmarshalingParamError struct {
	error
	paramName string
}

type RequiredParamError struct {
	error
	paramName string
}

type RequiredHeaderError struct {
	error
	paramName string
}

type InvalidParamFormatError struct {
	error
	paramName string
}

type TooManyValuesForParamError struct {
	error
	paramName string
}

// ParameterName is an interface that is implemented by error types that are
// relevant to a specific parameter.
type ParameterError interface {
	error
	// ParamName is the name of the parameter that the error is referring to.
	ParamName() string
}

func (err UnmarshalingParamError) ParamName() string     { return err.paramName }
func (err RequiredParamError) ParamName() string         { return err.paramName }
func (err RequiredHeaderError) ParamName() string        { return err.paramName }
func (err InvalidParamFormatError) ParamName() string    { return err.paramName }
func (err TooManyValuesForParamError) ParamName() string { return err.paramName }

type ServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      map[string]func(http.Handler) http.Handler
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

type ServerOption func(*ServerOptions)

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface, opts ...ServerOption) http.Handler {
	options := &ServerOptions{
		BaseURL:     "/",
		BaseRouter:  chi.NewRouter(),
		Middlewares: make(map[string]func(http.Handler) http.Handler),
		ErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
	}

	for _, f := range opts {
		f(options)
	}

	r := options.BaseRouter
	wrapper := ServerInterfaceWrapper{
		Handler:          si,
		Middlewares:      options.Middlewares,
		ErrorHandlerFunc: options.ErrorHandlerFunc,
	}

	r.Route(options.BaseURL, func(r chi.Router) {
		r.Get("/assets/{id}", wrapper.GetAsset)
		r.Post("/login", wrapper.Login)
		r.Get("/posts", wrapper.GetNextPosts)
		r.Get("/posts/liked", wrapper.GetLikedPosts)
		r.Delete("/posts/{id}", wrapper.DeletePost)
		r.Post("/register", wrapper.Register)
		r.Get("/users/self", wrapper.GetSelf)
		r.Get("/users/{id}", wrapper.GetUser)

	})
	return r
}

func WithRouter(r chi.Router) ServerOption {
	return func(s *ServerOptions) {
		s.BaseRouter = r
	}
}

func WithServerBaseURL(url string) ServerOption {
	return func(s *ServerOptions) {
		s.BaseURL = url
	}
}

func WithMiddleware(key string, middleware func(http.Handler) http.Handler) ServerOption {
	return func(s *ServerOptions) {
		s.Middlewares[key] = middleware
	}
}

func WithMiddlewares(middlewares map[string]func(http.Handler) http.Handler) ServerOption {
	return func(s *ServerOptions) {
		s.Middlewares = middlewares
	}
}

func WithErrorHandler(handler func(w http.ResponseWriter, r *http.Request, err error)) ServerOption {
	return func(s *ServerOptions) {
		s.ErrorHandlerFunc = handler
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZbW/bOBL+KwRvgb0rFNtJ89L14T6km6abQ7Y18tLdQ9YIaGlksaFILUnZUQP/98OQ",
	"kiVZjutm0xY43DdLoub1mWdm5AcaqjRTEqQ1dPhANZhMSQPu4lTp9I3WSuNFqKQFafEnyzLBQ2a5kv2P",
	"Rkm8Z8IEUoa/ftAQ0yH9W7+W3PdPTb+WuFgsAhqBCTXPUBAdOnUE8GmPLgL6TtlTlcvoG1pwAUblOgTC",
	"ZYTiISKTgjCSMc1SsKDJ33lMmCz+QbiRP1oSo4HO2kvQM9DPa+ujdl5LuM8gRPuM07sM2yIoZbsELs1p",
	"v+5uEzX5CKElGmyuJURESfSskhRQuGdpJgBfT8EYNgU6pKW6iYA5yTN0PNMqA225h8zy5AO1RebesJrL",
	"qbNMw5851xDR4c3y4HgR0FOlopGGGDTI0MtpSxX8zv9Y2nRDL3gINKCn3CR0HFBuITVr1AbVDaY1K7zB",
	"qMmdZVHEMSZMjFr6thfWCJKzZHhDjxNOrnLJaEAvmUiVRPOctcMbepmbhBN3Na7F+VR0YuTdri32sWrU",
	"JBPifUyHN1vBKFiNaqx0esujdblajIOtMUPiRt22IrJUQHMDWrIUE1ZjKeXGcDkly4fo/9lJF6+XUs1j",
	"we6AnJ20VNCfDl6+Gvx0sHtwuLd7sHd0cLhHgxVnAnq/M1U75c1YqchyGYHunZ1gAs/VlMtfwbKIWdZV",
	"/T7z+CBpeYRwGYo88r4LfLlHV4sAHbpl07L+2wKvEiDXBvTOMT5H3yMMIIqaYjC8vNrDMNeif9Q73O/t",
	"dlxzzDBSxnYrJlQz0LcJQ0g2yoaev/nlw6H87fVecfcqK9S/WXTxond09/OvkfzYlb8CgqYgD22ilRDO",
	"/h9e9f6Qf8iRBmsLEibAMnc/hd46uR52m1Dr08NTNu2UfpHB6zdGTWahPpx/fPsp5aPwisHbo9vpdfzm",
	"oMj/8/plwm7zy3Pzry/jBqE8UXfzdl4+IdwQmwCpTpJ5AhrcrUwZS+bMkJRF0M7iaS4EaKtkQH4+XhcP",
	"y6arXpbkEbQ440uccTDcLtArxMMjWr++TEIbDaXNY9f7RLw9HSH6HRttbtPtltBlrwnXNolYURENs3RI",
	"I2ZhTZm0vVu+OV54640pU97WAPcZ1135O5ansC6HaYNFNvnWphxMnLqDlfL6TcxGv0fv8iK2VryCyw+H",
	"R8ndxPx+sDs/v774dLVO/9PzXafamxJUvjecwlC51HXixGbMMt22/4tKdI0vE67aAn8BIVRA5kqL6C8x",
	"ius0LdHYE3Z8U9jBSHwWQC5SZTsrnR+7yQvCXHNbXKJCH5vXwDTo49wmy7EPBU/c7VpRYm3m6ZzL2Hlu",
	"uXXGvc9AHo/OiHfCUSrWxs6Vs5cGdAbaw5cOeoPeLrqoMpAs43RIX/YGvQH2J2YTZ0+fGQPW9B94tMDr",
	"Kbjmgel0dHaG3fot2GM85l4sJ1/j6rrby5w8cnZCrCIx2DDB5HB8ijqrOA19zOogWp1D0BiDVwM+Dtqr",
	"yN5gsDJWv+i/aE/SyyKdcMkcdjvdchHQ/cH+YzhZKuy3V49FQA+8+s1vNVcAB4c8TdEQF1DXIWIuqohN",
	"Cndnymcgcawh75TFNsKsP2AI00CkssQAJqHcRdClf7o3EakkzY07n6e+BeFjEmuVuisXrXvrpdpmsrhx",
	"p/zC0HdjjKvrcpZow8HxVRcLLsl/5uBCXWa5MedtneuAGluUhahTx/TrRGfMmLnSm2G0xEDj9GfUfR5p",
	"T1/gqtayZoU7V9MpRIRLYvIwBGPiXIjCrZL7g92vv0LuD3bJtWS5TZTmnyCqZ/p5ArJGGEhMuLuea9WY",
	"1gmTEanCTEKVYtmh8N7TC6bkTzq8GTfL51zhXEzy1rbQ0t8jxwQ94qb2g8fOaiRUBEU5u3EZKq0htCX2",
	"EfJmExO+g3s7coe2YEPPg8Yy7QsuY9MyKq7eAqI0gTSzRX3MV6vKlry5insNM9+bt8u4a+9/FdTLIXOT",
	"Jrd5dObOkmW3SH/jU8yzMaxEvpswGyZExcQnt85zHzfqaFO2z/FAle7vGsJnCojgxi5DQZz/Ve9xs04j",
	"ONVMEIEAC93wnLj7zuQtSsFtQ74evMCnDQZPhXrboGMhygg02bY0LCpZ9zsMBj6kvlnnWpdfBPSPprR2",
	"UrjZ4FFycxRtNQdTx5kYlYKSQEAYKCWVZKdhyo0tZ/i1vf6iOvH/dv+s7b6KK0Tr+v23IctHumtl2qb+",
	"6uGDj0zflNv+YxTqvgZ81SiL+Hk5sll6TU8/tyRdm3WFsnYqUHW9fiUe/B+qI/+F6ImDxHdb8JhnY99c",
	"uSYuK+26a38PuBljFP0/Kuug88Fv9mRAjkdnBNGC0Mm1KD8YmGG//5AoYzHViz7LeH+Gy/6Mac4mwuel",
	"eu57YsxygXkWKmQi8Z28i9dIpYzLCrOofMLCO5DVv03uD4LFfwMAAP//AjuZsjscAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
